name: Deploy nonprod

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
      SERVICE:
        required: false
        type: string
      DISPATCH_EVENT:
        required: true
        type: string
      DISPATCH_REPO:
        required: true
        type: string

    secrets:
      ORG_CI_TS_TOKEN:
        required: true

jobs:
  dispatch:
    name: dispatch
    runs-on: self-hosted-cpu
    if: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Collect commit metadata
        id: prepare
        shell: bash
        run: |
          message=$(echo "${{ github.event.head_commit.message }}" | head -1)

          if [ -z "${{ inputs.SERVICE }}" ]; then
            service=$(echo "${GITHUB_REPOSITORY#*/}" | tr _ -)
          else
            service=${{ inputs.SERVICE }}
          fi
    
          echo "service=${service}" >> $GITHUB_OUTPUT
          echo "message=${message}" >> $GITHUB_OUTPUT
          echo "repo=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Deploy dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ORG_CI_TS_TOKEN }}
          repository: ${{ inputs.DISPATCH_REPO }}
          event-type: ${{ inputs.DISPATCH_EVENT }}
          client-payload: |-
            {
            "msg": "${{ steps.prepare.outputs.message }}",
            "sender": "${{ github.event.sender.login }}",
            "repo": "${{ steps.prepare.outputs.repo }}",
            "service": "${{ steps.prepare.outputs.service }}",
            "image_tag": "${{ inputs.IMAGE_TAG }}"
            }
